# Generated by Django 2.0.5 on 2018-05-09 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Collection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True)),
                ('post_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('published_date', models.DateTimeField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('sports', 'SPORTS'), ('politics', 'POLITICS'), ('entertainment', 'ENTERTAINMENT'), ('business', 'BUSINESS'), ('tech', 'TECH'), ('health', 'HEALTH')], max_length=200)),
                ('country', models.CharField(blank=True, choices=[('AU', 'Australia'), ('NZ', 'New Zealand'), ('CN', 'Çhina'), ('IN', 'India'), ('ID', 'Indonesia'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('JP', 'Japan'), ('PH', 'Philippines'), ('VN', 'Vietnam'), ('IR', 'Iran'), ('TH', 'Thailand'), ('KR', 'South Korea'), ('AE', 'UAE'), ('NG', 'Nigeria'), ('ET', 'Ethopia'), ('EG', 'Egypt'), ('CG', 'Congo'), ('ZA', 'South Africa'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('SD', 'Sudan'), ('DZ', 'Algeria'), ('UG', 'Uganda'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('GH', 'Ghana'), ('AO', 'Angola'), ('CI', 'Ivory Coast'), ('RU', 'Russia'), ('DE', 'Germany'), ('TR', 'Turkey'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('ES', 'Spain'), ('UA', 'Ukraine'), ('PL', 'Poland'), ('RO', 'Romania'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('BR', 'Brazil'), ('CO', 'Colombia'), ('AR', 'Argentina'), ('PE', 'Peru'), ('VE', 'Venezuela'), ('US', 'United State'), ('MX', 'Mexico'), ('CA', 'Canada'), ('CU', 'Cuba'), ('HT', 'Haiti')], max_length=200)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-published_date',),
                'get_latest_by': 'published_date',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(to='dashboard.Post'),
        ),
    ]
